#ifndef USER_WEBAPI_H
#define USER_WEBAPI_H

#include "QtQmlIntegration/qqmlintegration.h"
#include <QObject>

class UserWebAPI : public QObject {
    Q_OBJECT
    QML_ELEMENT
    QML_SINGLETON

public:

    UserWebAPI(QObject *parent = nullptr);
    virtual ~UserWebAPI() override;

    static const QString ENDPOINT_USER_LOGIN;
    static const QString ENDPOINT_USER_LOGOUT;
    static const QString ENDPOINT_USER_REFRESH_TOKEN;
    static const QString ENDPOINT_USER_USERS;
    static const QString ENDPOINT_USER_USERGROUPS;
    static const QString ENDPOINT_USER_USERS_USERGROUPS;
    static const QString ENDPOINT_USER_USERS_PREFERENCES;
    static const QString ENDPOINT_USER_SITES;
    static const QString ENDPOINT_USER_PROJECTS;
    static const QString ENDPOINT_USER_SITEACCESS;
    static const QString ENDPOINT_USER_PROJECTACCESS;
    static const QString ENDPOINT_USER_DEVICES;
    static const QString ENDPOINT_USER_DEVICES_SITES;
    static const QString ENDPOINT_USER_DEVICES_PROJECTS;
    static const QString ENDPOINT_USER_DEVICES_PARTICIPANTS;
    static const QString ENDPOINT_USER_DEVICESUBTYPES;
    static const QString ENDPOINT_USER_DEVICETYPES;
    static const QString ENDPOINT_USER_PARTICIPANTS;
    static const QString ENDPOINT_USER_GROUPS;
    static const QString ENDPOINT_USER_SESSIONS;
    static const QString ENDPOINT_USER_SESSIONTYPES;
    static const QString ENDPOINT_USER_SESSIONTYPES_PROJECTS;
    static const QString ENDPOINT_USER_SESSIONTYPES_SITES;
    static const QString ENDPOINT_USER_SESSIONS_EVENTS;
    static const QString ENDPOINT_USER_SERVICES;
    static const QString ENDPOINT_USER_SERVICES_PROJECTS;
    static const QString ENDPOINT_USER_SERVICES_SITES;
    static const QString ENDPOINT_USER_SERVICES_ACCESS;
    static const QString ENDPOINT_USER_SERVICES_CONFIGS;
    static const QString ENDPOINT_USER_SERVICES_ROLES;
    static const QString ENDPOINT_USER_STATS;
    static const QString ENDPOINT_USER_ASSETS;
    static const QString ENDPOINT_USER_TESTTYPES;
    static const QString ENDPOINT_USER_TESTTYPES_SITES;
    static const QString ENDPOINT_USER_TESTTYPES_PROJECTS;
    static const QString ENDPOINT_USER_TESTS;
    static const QString ENDPOINT_USER_DISCONNECT;
    static const QString ENDPOINT_USER_SESSIONS_MANAGER;
    static const QString ENDPOINT_USER_USERS_ONLINE;
    static const QString ENDPOINT_USER_PARTICIPANTS_ONLINE;
    static const QString ENDPOINT_USER_DEVICES_ONLINE;
    static const QString ENDPOINT_USER_VERSIONS;
    static const QString ENDPOINT_USER_FORMS;

    // Getters
    static QString getENDPOINT_USER_LOGIN();
    static QString getENDPOINT_USER_LOGOUT();
    static QString getENDPOINT_USER_REFRESH_TOKEN();
    static QString getENDPOINT_USER_USERS();
    static QString getENDPOINT_USER_USERGROUPS();
    static QString getENDPOINT_USER_USERS_PREFERENCES();
    static QString getENDPOINT_USER_SITES();
    static QString getENDPOINT_USER_PROJECTS();
    static QString getENDPOINT_USER_SITEACCESS();
    static QString getENDPOINT_USER_PROJECTACCESS();
    static QString getENDPOINT_USER_DEVICES();
    static QString getENDPOINT_USER_DEVICES_SITES();
    static QString getENDPOINT_USER_DEVICES_PROJECTS();
    static QString getENDPOINT_USER_DEVICES_PARTICIPANTS();
    static QString getENDPOINT_USER_DEVICESUBTYPES();
    static QString getENDPOINT_USER_DEVICETYPES();
    static QString getENDPOINT_USER_PARTICIPANTS();
    static QString getENDPOINT_USER_GROUPS();
    static QString getENDPOINT_USER_SESSIONS();
    static QString getENDPOINT_USER_SESSIONTYPES();
    static QString getENDPOINT_USER_SESSIONTYPES_PROJECTS();
    static QString getENDPOINT_USER_SESSIONTYPES_SITES();
    static QString getENDPOINT_USER_SESSIONS_EVENTS();
    static QString getENDPOINT_USER_SERVICES();
    static QString getENDPOINT_USER_SERVICES_PROJECTS();
    static QString getENDPOINT_USER_SERVICES_SITES();
    static QString getENDPOINT_USER_SERVICES_ACCESS();
    static QString getENDPOINT_USER_SERVICES_CONFIGS();
    static QString getENDPOINT_USER_SERVICES_ROLES();
    static QString getENDPOINT_USER_STATS();
    static QString getENDPOINT_USER_ASSETS();
    static QString getENDPOINT_USER_TESTTYPES();
    static QString getENDPOINT_USER_TESTTYPES_SITES();
    static QString getENDPOINT_USER_TESTTYPES_PROJECTS();
    static QString getENDPOINT_USER_TESTS();
    static QString getENDPOINT_USER_DISCONNECT();
    static QString getENDPOINT_USER_SESSIONS_MANAGER();
    static QString getENDPOINT_USER_USERS_ONLINE();
    static QString getENDPOINT_USER_PARTICIPANTS_ONLINE();
    static QString getENDPOINT_USER_DEVICES_ONLINE();
    static QString getENDPOINT_USER_VERSIONS();
    static QString getENDPOINT_USER_FORMS();

private:
    Q_PROPERTY(QString ENDPOINT_USER_LOGIN READ getENDPOINT_USER_LOGIN CONSTANT FINAL)
    Q_PROPERTY(QString ENDPOINT_USER_LOGOUT READ getENDPOINT_USER_LOGOUT CONSTANT FINAL)
    Q_PROPERTY(QString ENDPOINT_USER_REFRESH_TOKEN READ getENDPOINT_USER_REFRESH_TOKEN CONSTANT FINAL)
    Q_PROPERTY(QString ENDPOINT_USER_USERS READ getENDPOINT_USER_USERS CONSTANT FINAL)
    Q_PROPERTY(QString ENDPOINT_USER_USERGROUPS READ getENDPOINT_USER_USERGROUPS CONSTANT FINAL)
    Q_PROPERTY(QString ENDPOINT_USER_USERS_PREFERENCES READ getENDPOINT_USER_USERS_PREFERENCES CONSTANT FINAL)
    Q_PROPERTY(QString ENDPOINT_USER_SITES READ getENDPOINT_USER_SITES CONSTANT FINAL)
    Q_PROPERTY(QString ENDPOINT_USER_PROJECTS READ getENDPOINT_USER_PROJECTS CONSTANT FINAL)
    Q_PROPERTY(QString ENDPOINT_USER_SITEACCESS READ getENDPOINT_USER_SITEACCESS CONSTANT FINAL)
    Q_PROPERTY(QString ENDPOINT_USER_PROJECTACCESS READ getENDPOINT_USER_PROJECTACCESS CONSTANT FINAL)
    Q_PROPERTY(QString ENDPOINT_USER_DEVICES READ getENDPOINT_USER_DEVICES CONSTANT FINAL)
    Q_PROPERTY(QString ENDPOINT_USER_DEVICES_SITES READ getENDPOINT_USER_DEVICES_SITES CONSTANT FINAL)
    Q_PROPERTY(QString ENDPOINT_USER_DEVICES_PROJECTS READ getENDPOINT_USER_DEVICES_PROJECTS CONSTANT FINAL)
    Q_PROPERTY(QString ENDPOINT_USER_DEVICES_PARTICIPANTS READ getENDPOINT_USER_DEVICES_PARTICIPANTS CONSTANT FINAL)
    Q_PROPERTY(QString ENDPOINT_USER_DEVICESUBTYPES READ getENDPOINT_USER_DEVICESUBTYPES CONSTANT FINAL)
    Q_PROPERTY(QString ENDPOINT_USER_DEVICETYPES READ getENDPOINT_USER_DEVICETYPES CONSTANT FINAL)
    Q_PROPERTY(QString ENDPOINT_USER_PARTICIPANTS READ getENDPOINT_USER_PARTICIPANTS CONSTANT FINAL)
    Q_PROPERTY(QString ENDPOINT_USER_GROUPS READ getENDPOINT_USER_GROUPS CONSTANT FINAL)
    Q_PROPERTY(QString ENDPOINT_USER_SESSIONS READ getENDPOINT_USER_SESSIONS CONSTANT FINAL)
    Q_PROPERTY(QString ENDPOINT_USER_SESSIONTYPES READ getENDPOINT_USER_SESSIONTYPES CONSTANT FINAL)
    Q_PROPERTY(QString ENDPOINT_USER_SESSIONTYPES_PROJECTS READ getENDPOINT_USER_SESSIONTYPES_PROJECTS CONSTANT FINAL)
    Q_PROPERTY(QString ENDPOINT_USER_SESSIONTYPES_SITES READ getENDPOINT_USER_SESSIONTYPES_SITES CONSTANT FINAL)
    Q_PROPERTY(QString ENDPOINT_USER_SESSIONS_EVENTS READ getENDPOINT_USER_SESSIONS_EVENTS CONSTANT FINAL)
    Q_PROPERTY(QString ENDPOINT_USER_SERVICES READ getENDPOINT_USER_SERVICES CONSTANT FINAL)
    Q_PROPERTY(QString ENDPOINT_USER_SERVICES_PROJECTS READ getENDPOINT_USER_SERVICES_PROJECTS CONSTANT FINAL)
    Q_PROPERTY(QString ENDPOINT_USER_SERVICES_SITES READ getENDPOINT_USER_SERVICES_SITES CONSTANT FINAL)
    Q_PROPERTY(QString ENDPOINT_USER_SERVICES_ACCESS READ getENDPOINT_USER_SERVICES_ACCESS CONSTANT FINAL)
    Q_PROPERTY(QString ENDPOINT_USER_SERVICES_CONFIGS READ getENDPOINT_USER_SERVICES_CONFIGS CONSTANT FINAL)
    Q_PROPERTY(QString ENDPOINT_USER_SERVICES_ROLES READ getENDPOINT_USER_SERVICES_ROLES CONSTANT FINAL)
    Q_PROPERTY(QString ENDPOINT_USER_STATS READ getENDPOINT_USER_STATS CONSTANT FINAL)
    Q_PROPERTY(QString ENDPOINT_USER_ASSETS READ getENDPOINT_USER_ASSETS CONSTANT FINAL)
    Q_PROPERTY(QString ENDPOINT_USER_TESTTYPES READ getENDPOINT_USER_TESTTYPES CONSTANT FINAL)
    Q_PROPERTY(QString ENDPOINT_USER_TESTTYPES_SITES READ getENDPOINT_USER_TESTTYPES_SITES CONSTANT FINAL)
    Q_PROPERTY(QString ENDPOINT_USER_TESTTYPES_PROJECTS READ getENDPOINT_USER_TESTTYPES_PROJECTS CONSTANT FINAL)
    Q_PROPERTY(QString ENDPOINT_USER_TESTS READ getENDPOINT_USER_TESTS CONSTANT FINAL)
    Q_PROPERTY(QString ENDPOINT_USER_DISCONNECT READ getENDPOINT_USER_DISCONNECT CONSTANT FINAL)
    Q_PROPERTY(QString ENDPOINT_USER_SESSIONS_MANAGER READ getENDPOINT_USER_SESSIONS_MANAGER CONSTANT FINAL)
    Q_PROPERTY(QString ENDPOINT_USER_USERS_ONLINE READ getENDPOINT_USER_USERS_ONLINE CONSTANT FINAL)
    Q_PROPERTY(QString ENDPOINT_USER_PARTICIPANTS_ONLINE READ getENDPOINT_USER_PARTICIPANTS_ONLINE CONSTANT FINAL)
    Q_PROPERTY(QString ENDPOINT_USER_DEVICES_ONLINE READ getENDPOINT_USER_DEVICES_ONLINE CONSTANT FINAL)
    Q_PROPERTY(QString ENDPOINT_USER_VERSIONS READ getENDPOINT_USER_VERSIONS CONSTANT FINAL)
    Q_PROPERTY(QString ENDPOINT_USER_FORMS READ getENDPOINT_USER_FORMS CONSTANT FINAL)
};


#endif // USER_WEBAPI_H
