#ifndef PARTICIPANT_WEBAPI_H
#define PARTICIPANT_WEBAPI_H

#include "QtQmlIntegration/qqmlintegration.h"
#include <QObject>

class ParticipantWebAPI : public QObject {
    Q_OBJECT
    QML_ELEMENT
    QML_SINGLETON

public:

    ParticipantWebAPI(QObject *parent = nullptr);
    virtual ~ParticipantWebAPI() override;

    static const QString ENDPOINT_PARTICIPANT_ASSETS;
    static const QString ENDPOINT_PARTICIPANT_DEVICES;
    static const QString ENDPOINT_PARTICIPANT_LOGIN;
    static const QString ENDPOINT_PARTICIPANT_LOGOUT;
    static const QString ENDPOINT_PARTICIPANT_PARTICIPANTS;
    static const QString ENDPOINT_PARTICIPANT_REFRESH_TOKEN;
    static const QString ENDPOINT_PARTICIPANT_SESSIONS;


    // Getters
    static QString getENDPOINT_PARTICIPANT_ASSETS();
    static QString getENDPOINT_PARTICIPANT_DEVICES();
    static QString getENDPOINT_PARTICIPANT_LOGIN();
    static QString getENDPOINT_PARTICIPANT_LOGOUT();
    static QString getENDPOINT_PARTICIPANT_PARTICIPANTS();
    static QString getENDPOINT_PARTICIPANT_REFRESH_TOKEN();
    static QString getENDPOINT_PARTICIPANT_SESSIONS();

private:

    Q_PROPERTY(QString ENDPOINT_PARTICIPANT_ASSETS READ getENDPOINT_PARTICIPANT_ASSETS CONSTANT FINAL);
    Q_PROPERTY(QString ENDPOINT_PARTICIPANT_DEVICES READ getENDPOINT_PARTICIPANT_DEVICES CONSTANT FINAL);
    Q_PROPERTY(QString ENDPOINT_PARTICIPANT_LOGIN READ getENDPOINT_PARTICIPANT_LOGIN CONSTANT FINAL);
    Q_PROPERTY(QString ENDPOINT_PARTICIPANT_LOGOUT READ getENDPOINT_PARTICIPANT_LOGOUT CONSTANT FINAL);
    Q_PROPERTY(QString ENDPOINT_PARTICIPANT_PARTICIPANTS READ getENDPOINT_PARTICIPANT_PARTICIPANTS CONSTANT FINAL);
    Q_PROPERTY(QString ENDPOINT_PARTICIPANT_REFRESH_TOKEN READ getENDPOINT_PARTICIPANT_REFRESH_TOKEN CONSTANT FINAL);
    Q_PROPERTY(QString ENDPOINT_PARTICIPANT_SESSIONS READ getENDPOINT_PARTICIPANT_SESSIONS CONSTANT FINAL);
};


#endif // PARTICIPANT_WEBAPI_H
